version: "3.8"

services:
  broker:
    image: redis:6.0.5
    command: redis-server
    ports:
      - "6379:6379"
    networks:
      - main

  db:
    image: postgres:12.3
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - main

  web:
    build: .
    image: web
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - broker
    networks:
      - main
    restart: on-failure

  worker:
    image: web
    command: celery -A celerie worker -l info
    depends_on:
      - web
      - db
      - broker
    networks:
      - main

  scheduler:
    image: web
    command: celery -A celerie beat -l info
    depends_on:
      - web
      - db
      - broker
    networks:
      - main

# creates a data image that will persist between restarts
volumes:
  postgres_data:

networks:
  main:
