version: "3"

services:
  redis:
    image: redis:6.0.5
    command: redis-server
    ports:
      - "6379:6379"
  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - redis
  celery:
    build: .
    command: celery -A celerie worker -B
    volumes:
      - .:/code
    links:
      - redis
    depends_on:
      - web
      - redis
